<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeForm;
use Drupal\node\NodeInterface;

// Implements HOOK_form_alter
function citizen_preview_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!$form_state->getFormObject() instanceof NodeForm) {
    return;
  }
  $node = $form_state->getFormObject()->getEntity();
  if ($node instanceof NodeInterface) {
    $preview_mode = $node->type->entity->getPreviewMode();

    // Add the js library button to the node edit form
    if (isset($form["actions"]["preview"])) {
      $form['#attached']['library'][] = 'citizen_preview/preview';
      $form['actions']['citizen_preview'] = [
        '#type' => 'link',
        '#title' => t('Preview'),
        '#access' => $preview_mode != DRUPAL_DISABLED && ($node->access('create') || $node->access('update')),
        '#url' => Url::fromRoute('citizen_preview.form'),
        '#attributes' => [
          'class' => [
            'fixed-preview',
            'button',
            'button--primary'
          ],
        ],
      ];
    }
  }
}
